---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: tkw
spec:
  rules:
  - http:
      paths:
      - path: /test-kubernetes-war
        backend:
          serviceName: tkw
          servicePort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: tkw
spec:
  selector:
    app: tkw
    tier: frontend
  ports:
  - protocol: TCP
    port: 8080
    targetPort: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tkw
  annotations:
    fluxcd.io/automated: 'true'
spec:
  selector:
    matchLabels:
      app: tkw
      tier: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: tkw
        tier: frontend
    spec:
      containers:
      - name: tkw
        image: "astonunion.azurecr.io/tkw:1.9-SNAPSHOT"
        ports:
        - name: http
          containerPort: 8080
        volumeMounts:
        - name: tkw-config-volume
          mountPath: /tmp/conf
      volumes:
      - name: tkw-config-volume
        configMap:
          name: tkw-config
      imagePullSecrets:
      - name: astonunion
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: tkw-config
data:
  tkw.path: /test-kubernetes-war
  app.tkw.properties: |-
    a=aa3
    b=bb4
  env: |-
    JAVA_OPTS=''
    TEST=1
