apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: demo
spec:
  rules:
  - http:
      paths:
      - path: /aa
        backend:
          serviceName: hello
          servicePort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: hello
spec:
  selector:
    app: hello
    tier: backend
  ports:
  - protocol: TCP
    port: 80
    targetPort: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello
spec:
  selector:
    matchLabels:
      app: hello
      tier: backend
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: hello
        tier: backend
        track: stable
    spec:
      containers:
        - name: hello
          image: "gcr.io/google-samples/hello-go-gke:1.0"
          ports:
            - name: http
              containerPort: 80
          volumeMounts:
          - name: config-volume
            mountPath: /tmp/props/twk
          volumeMounts:
          - name: config-volume-mail
            mountPath: /tmp/props/mail-all
          volumeMounts:
          - name: config-volume-jdbc
            mountPath: /tmp/props/jdbc
      volumes:
        - name: config-volume-hello/jdbc
          configMap:
            name: config-hello
      volumes:
        - name: config-volume-hello-mail
          configMap:
            name: config-hello-mail
      volumes:
        - name: config-volume-hello-jdbc
          configMap:
            name: config-hello-jdbc
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-hello
data:
  color:purple
  how:fairlyNice
  textmode:true
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-hello-mail
data:
  color:purple
  how:fairlyNice
  textmode:true
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-hello-jdbc
data:
  color:purple
  how:fairlyNice
  textmode:true
